# Generated by Django 4.2.14 on 2024-08-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='when_published',
        ),
    ]
